version: 2.1

jobs:
  build_dart:
    docker:
      - image: google/dart:latest

    steps:
      - checkout
      - run:
          name: Hello World in Dart
          command: dart -e "print('Hello, World! (Dart)')"

  build_ruby:
    docker:
      - image: ruby:latest

    steps:
      - checkout
      - run:
          name: Hello World in Ruby
          command: ruby -e "puts 'Hello, World! (Ruby)'"

  build_scala:
    docker:
      - image: hseeberger/scala-sbt:11.0.12_1.5.5_2.13.6

    steps:
      - checkout
      - run:
          name: Hello World in Scala
          command: scala -e "println('Hello, World! (Scala)')"

  build_typescript:
    docker:
      - image: node:latest

    steps:
      - checkout
      - run:
          name: Hello World in TypeScript
          command: echo "console.log('Hello, World! (TypeScript)');"

workflows:
  version: 2
  build_workflow:
    jobs:
      - build_dart:
          filters:
            branches:
              only:
                - feature/dart

      - build_ruby:
          filters:
            branches:
              only:
                - feature/ruby

      - build_scala:
          filters:
            branches:
              only:
                - feature/scala

      - build_typescript:
          filters:
            branches:
              only:
                - feature/typescript
